name: Test Package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Tests the code"
        run: |
          pip install pipenv
          pipenv install
          pipenv run gitlint
          pipenv run pylint setup.py gitea_auto_update
          pipenv run python -m unittest